### ISSUE TITLE
differences in amount of code between oidc-client for browser based javascript 

### ISSUE THREAD

**Issue by jaunuolis** [edwinf/oidc-client-node#6]
This library is very lightweight, main file has about 600 lines of code + some small libraries like bluebird.
This is a very small amount of code compared  to library for client-side, browser-based JavaScript client  https://github.com/IdentityModel/oidc-client-js .

Why is there such a huge difference in the amount of code between these two libraries?

**Comment by edwinf** [comment]
Since this is server side only, i can make use of node libraries and built in functionality.  I can also ignore some things that client side libraries have to deal with such as state, etc, by having the actual writer of the nodejs functions deal with those issues (as we did in our own app). That functionality doesn't belong in the server side library where that functionality would be better handled by express middleware, etc, but would be required in the client side one.

**Comment by jaunuolis** [comment]
I see. 
We are using identity server for authentication, asp.net web api for backend and AngularJS for front end. Instead of using oidc-client for browser based javasscript applications, we want to add a node js server in between AngularJS and asp.net web api. This node js server would be responsible for authentication part by using the library you created. Also, we could benefit with other node js things in this case in the future. Are there any cons with such aproach?

**Comment by edwinf** [comment]
I can't speak much to your architecture or pros /cons really without knowing all of your requirements.  My thoughts when reading your question were if you already had a web api service in place, why you wouldn't just leverage a couple mvc controllers that would use the identity server middleware instead of rolling a new server with your own routing logic, etc..., but again, I can't really comment because I don't know all of your requirements :smile:
